spring:
  cloud:
    gateway:
      routes:
      - id: servicio-productos
        uri: lb://servicio-productos
        predicates:
          - Path=/api/productos/**
    
          - Method=GET, POST
          - 
        filters:
          - StripPrefix=2
          - name: Ejemplo
            args:
              mensaje: Hola, mi mensaje personalizado
              cookieNombre: usuario
              cookieValor: JorgeMeza
      - id: servicio-items
        uri: lb://servicio-item
        predicates:
          - Path=/api/items/**
        filters:
          - StripPrefix=2
          - AddRequestHeader=token-request, 123456
          - AddResponseHeader=token-response, 1234567
          - AddRequestParameter=nombre, jorge
          
          
          
               
          